### ISSUE TITLE
请教：关于侧边栏(sidebar)为左边显示的设置方法

### ISSUE THREAD

**Issue by Mashiro-Sorata** [zhuzhuyule/zhuzhuyule.github.io#1]
在看到博主您的博客侧边栏显示在左边，但是我更改设置到最后还有一个小bug。很抱歉在您百忙之中打扰到您，但是关于这个问题我实在解决不了，能占用您的一点时间帮一下忙吗？万分感谢！
***
# 我的侧边栏设置：
* 1.更改页面变化方向：

<p>首先，打开next/source/js/src文件夹下的motion.js文件
Ctrl+f查找‘paddingRight’；把所有（2个）PaddingRight更改为paddingLeft即可。</p>

<code>{paddingLeft: SIDEBAR_WIDTH}</code>
<code>NexT.utils.isDesktop() && $('body').velocity('stop').velocity({paddingLeft: 0});</code>

* 2.更改所有和sidebar相关的元素位置
<p> (1)更改sidebar：
打开next/source/css/_common/components/sidebar文件夹下的sidebar.styl文件，将.sidebar{}内的right: 0; 改为left: 0;</p>

<code>.sidebar {
  position: fixed;
  left: 0;}</code>

<p>(2)打开相同路径下的sidebar-toggle.styl文件，将.sidebar-toggle{}内的right: $b2t-position-right; 改为left: $b2t-position-right;</p>

<code>.sidebar-toggle {
  position: fixed;
  left: $b2t-position-right;}</code>
<p>(3)返回上一个文件夹，打开back-to-top.styl文件，将.back-to-top {}内的right: $b2t-position-right;改为left: $b2t-position-right;</p>

<code>.back-to-top {
  box-sizing: border-box;
  position: fixed;
  bottom: $b2t-position-bottom;
  left: $b2t-position-right;}</code>
***
# 存在的问题
<p>减小浏览器的宽度时，当宽度小于一定值（990px左右）的时候，侧边栏（sidebar）会隐藏，但是此时网页头（header）以及底部（footer）左侧还是停留在原处。形如下图：</p>

![image](https://user-images.githubusercontent.com/30523722/28816488-a368bcdc-76d7-11e7-8284-80fab8c7bc6b.png)

希望博主能够抽取一点宝贵的空闲时间帮一下忙，再次感谢！

**Comment by zhuzhuyule** [comment]
我都修改有：
##### 1.文件 `sidebar.styl` 修改
```
.sidebar {
  position: fixed;
  right: 0;
  top: 0;
  bottom: 0;

  width: 0;
  z-index: $zindex-4;
  box-shadow: inset 0 2px 6px black;
  background: $black-deep;
  -webkit-transform: translateZ(0); 
  
  +tablet() {
    display: none !important;
  }
  +mobile() {
    display: none !important;
  }
}
```

##### 2.文件 `motion.js` 还需要修改： Line54~Line74
```
  var sidebarToggleLine1st = new SidebarToggleLine({
    el: '.sidebar-toggle-line-first',
    status: {
      arrow: {width: '50%', rotateZ: '45deg', top: '2px', left:'50%'},
      close: {width: '100%', rotateZ: '-45deg', top: '5px', left: '0px'}
    }
  });
  var sidebarToggleLine2nd = new SidebarToggleLine({
    el: '.sidebar-toggle-line-middle',
    status: {
      arrow: {width: '90%', left: '2px'},
      close: {opacity: 0, left: '0px'}
    }
  });
  var sidebarToggleLine3rd = new SidebarToggleLine({
    el: '.sidebar-toggle-line-last',
    status: {
      arrow: {width: '50%', rotateZ: '-45deg', top: '-2px', left: '50%'},
      close: {width: '100%', rotateZ: '45deg', top: '-5px', left: '0px'}
    }
  });
```

其他修改没问题，你试试。

**Comment by Mashiro-Sorata** [comment]
抱歉才看到，没注意邮件提示，感谢博主解答！我以为回答的希望渺茫了哈哈，先粉一波~
问题在关闭issue的时候就已经解决了。
***
你给的sidebar.styl我文件里就是默认值，应该没问题，sidebarToggle我也修改了下样式(把插换成了箭头)，但是变化页面大小的时候还是存在页面没居中的问题。<br>
问题出在改变页面大小的时候，sidebar虽然隐藏了，但是body的paddingleft还是存在。<br>
我的做法是加入了onresize事件监测页面变化，根据页面大小调整body的paddingleft。<br>
最后打一波广告，里面是[我的设置](http://mashirosorata.vicp.io/HEXO-NEXT%E4%B8%BB%E9%A2%98%E4%B8%AA%E6%80%A7%E5%8C%96%E9%85%8D%E7%BD%AE.html)
