### ISSUE TITLE
怎样设置主页文章标题跟文章不一样啊

### ISSUE THREAD

**Issue by anson2416** [zhuzhuyule/zhuzhuyule.github.io#2]
你好，我在`hexo\themes\next\source\css\_common\components\post\post-title.styl`配置添加css代码模拟你博客的文章标题样式。但是该样式会应用到博客主页那里。请问怎样设置才能够实现css效果只应用在文章主页。

```css
  background-color: #b9d3ee;
  border-radius:.3em;
  line-height:1em;
  padding-bottom:.12em;
  padding-top:.12em;
  box-shadow:2px 2px 7px #9fb6cd;
```

**Comment by zhuzhuyule** [comment]
因为这下样式最后都是会合并的，所以你设置的这些样式都会统一显示，不好调整的。
