### ISSUE TITLE
请问下怎样实现代码块里面高亮一行

### ISSUE THREAD

**Issue by anson2416** [zhuzhuyule/zhuzhuyule.github.io#3]
就跟你的博客一样，用虚线highlight一行方便阅读。

**Comment by zhuzhuyule** [comment]
实线虚线，或者高亮背景显示代码需要修改node_modules插件：
`.\node_modules_modify\hexo\lib\plugins\filter\before_post_render\backtick_code_block.js`文件，如果你需要，我给你贴出来详细内容，或者直接写个博文。

**Comment by anson2416** [comment]
@zhuzhuyule 如果你不介意的话，能不能指教下？我刚学Javascript。

**Comment by anson2416** [comment]
对了 能不能教一下怎样实现实线虚线？

**Comment by zhuzhuyule** [comment]
这个要改 Node 的代码，步骤麻烦一些。

**Comment by zhuzhuyule** [comment]
@anson2416 [代码](https://github.com/zhuzhuyule/hexo-blog-modify)我已经上传了，博客好了@你。

**Comment by zhuzhuyule** [comment]
@anson2416  博客上传了，你可以看看了。
[HEXO下的语法高亮拓展修改](http://zhuzhuyule.xyz/2017/09/09/HEXO/HEXO%E4%B8%8B%E7%9A%84%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE%E6%8B%93%E5%B1%95%E4%BF%AE%E6%94%B9/)
